// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using firm_registry_api.Data;

#nullable disable

namespace firm_registry_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251026175712_o1")]
    partial class o1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ActivityCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActivityGroupId");

                    b.ToTable("ActivityCodes");
                });

            modelBuilder.Entity("ActivityGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ActivityGroups");
                });

            modelBuilder.Entity("firm_registry_api.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("firm_registry_api.Models.CompanyRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityCodeId")
                        .HasColumnType("integer");

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<string>("AdminNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Documents")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActivityCodeId");

                    b.HasIndex("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("CompanyRequests");

                    b.HasDiscriminator<string>("CompanyType").HasValue("CompanyRequest");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("firm_registry_api.Models.Founder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyRequestId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("JointStockCompanyRequestId")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LimitedCompanyRequestId")
                        .HasColumnType("integer");

                    b.Property<int?>("LimitedPartnershipRequestId")
                        .HasColumnType("integer");

                    b.Property<int?>("LimitedPartnershipRequestId1")
                        .HasColumnType("integer");

                    b.Property<int?>("PartnershipRequestId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Share")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CompanyRequestId");

                    b.HasIndex("JointStockCompanyRequestId");

                    b.HasIndex("LimitedCompanyRequestId");

                    b.HasIndex("LimitedPartnershipRequestId");

                    b.HasIndex("LimitedPartnershipRequestId1");

                    b.HasIndex("PartnershipRequestId");

                    b.ToTable("Founders");
                });

            modelBuilder.Entity("firm_registry_api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Residence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("firm_registry_api.Models.EntrepreneurRequest", b =>
                {
                    b.HasBaseType("firm_registry_api.Models.CompanyRequest");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.HasIndex("OwnerId");

                    b.HasDiscriminator().HasValue("Entrepreneur");
                });

            modelBuilder.Entity("firm_registry_api.Models.JointStockCompanyRequest", b =>
                {
                    b.HasBaseType("firm_registry_api.Models.CompanyRequest");

                    b.PrimitiveCollection<List<string>>("BoardOfDirectors")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<decimal>("ShareCapital")
                        .HasColumnType("numeric");

                    b.HasDiscriminator().HasValue("JointStockCompany");
                });

            modelBuilder.Entity("firm_registry_api.Models.LimitedCompanyRequest", b =>
                {
                    b.HasBaseType("firm_registry_api.Models.CompanyRequest");

                    b.Property<string>("DirectorFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ShareCapital")
                        .HasColumnType("numeric");

                    b.ToTable("CompanyRequests", t =>
                        {
                            t.Property("ShareCapital")
                                .HasColumnName("LimitedCompanyRequest_ShareCapital");
                        });

                    b.HasDiscriminator().HasValue("LimitedCompany");
                });

            modelBuilder.Entity("firm_registry_api.Models.LimitedPartnershipRequest", b =>
                {
                    b.HasBaseType("firm_registry_api.Models.CompanyRequest");

                    b.HasDiscriminator().HasValue("LimitedPartnership");
                });

            modelBuilder.Entity("firm_registry_api.Models.PartnershipRequest", b =>
                {
                    b.HasBaseType("firm_registry_api.Models.CompanyRequest");

                    b.HasDiscriminator().HasValue("Partnership");
                });

            modelBuilder.Entity("ActivityCode", b =>
                {
                    b.HasOne("ActivityGroup", "ActivityGroup")
                        .WithMany("ActivityCodes")
                        .HasForeignKey("ActivityGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityGroup");
                });

            modelBuilder.Entity("firm_registry_api.Models.CompanyRequest", b =>
                {
                    b.HasOne("ActivityCode", "ActivityCode")
                        .WithMany()
                        .HasForeignKey("ActivityCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("firm_registry_api.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("firm_registry_api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityCode");

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("firm_registry_api.Models.Founder", b =>
                {
                    b.HasOne("firm_registry_api.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("firm_registry_api.Models.CompanyRequest", "CompanyRequest")
                        .WithMany()
                        .HasForeignKey("CompanyRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("firm_registry_api.Models.JointStockCompanyRequest", null)
                        .WithMany("Shareholders")
                        .HasForeignKey("JointStockCompanyRequestId");

                    b.HasOne("firm_registry_api.Models.LimitedCompanyRequest", null)
                        .WithMany("Founders")
                        .HasForeignKey("LimitedCompanyRequestId");

                    b.HasOne("firm_registry_api.Models.LimitedPartnershipRequest", null)
                        .WithMany("GeneralPartners")
                        .HasForeignKey("LimitedPartnershipRequestId");

                    b.HasOne("firm_registry_api.Models.LimitedPartnershipRequest", null)
                        .WithMany("LimitedPartners")
                        .HasForeignKey("LimitedPartnershipRequestId1");

                    b.HasOne("firm_registry_api.Models.PartnershipRequest", null)
                        .WithMany("Partners")
                        .HasForeignKey("PartnershipRequestId");

                    b.Navigation("Address");

                    b.Navigation("CompanyRequest");
                });

            modelBuilder.Entity("firm_registry_api.Models.EntrepreneurRequest", b =>
                {
                    b.HasOne("firm_registry_api.Models.Founder", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ActivityGroup", b =>
                {
                    b.Navigation("ActivityCodes");
                });

            modelBuilder.Entity("firm_registry_api.Models.JointStockCompanyRequest", b =>
                {
                    b.Navigation("Shareholders");
                });

            modelBuilder.Entity("firm_registry_api.Models.LimitedCompanyRequest", b =>
                {
                    b.Navigation("Founders");
                });

            modelBuilder.Entity("firm_registry_api.Models.LimitedPartnershipRequest", b =>
                {
                    b.Navigation("GeneralPartners");

                    b.Navigation("LimitedPartners");
                });

            modelBuilder.Entity("firm_registry_api.Models.PartnershipRequest", b =>
                {
                    b.Navigation("Partners");
                });
#pragma warning restore 612, 618
        }
    }
}
